import { LivingContext } from "../types/living-context";

/**
 * ContextRenderer: Utility to render human-readable Markdown from the LivingContext JSON.
 */
export class ContextRenderer {
  public static renderPRD(context: LivingContext): string {
    return `# Product Requirements Document

## Project Overview
**Project Name:** ${context.metadata?.projectConfig?.name || "The App"}
**Description:** ${context.metadata?.projectConfig?.description || "A feature-rich application"}

## Core Purpose
${context.prd?.problemStatement || "To provide high-quality AI-driven development capabilities."}

## Goals
${context.prd?.goals?.map(g => `- ${g}`).join("\n") || "- Automate development workflows\n- Enhance context awareness"}

## Non-Goals
${context.prd?.nonGoals?.map(g => `- ${g}`).join("\n") || "N/A"}

## Target Audience
${context.prd?.targetAudience || "Developers and product teams"}

## Success Metrics
${context.prd?.successMetrics?.map(m => `- ${m}`).join("\n") || "- Increased development velocity\n- Improved code quality"}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderFeatures(context: LivingContext): string {
    if (!context.features || !Array.isArray(context.features)) return "# Product Features\n\nNo features defined yet.";

    return `# Product Features

${context.features.map(f => `
### ${f.name || "Unnamed Feature"} (${(f.priority || "medium").toUpperCase()})
**Description:** ${f.description || "N/A"}
**Value:** ${f.userValue || "N/A"}
**Acceptance Criteria:**
${f.acceptanceCriteria?.map(ac => `- [ ] ${ac}`).join("\n") || "- N/A"}
**Dependencies:** ${f.dependencies?.join(", ") || "None"}
`).join("\n---")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderTechnicalSpecs(context: LivingContext): string {
    if (!context.specs) return "# Technical Specifications\n\nNo technical specifications defined yet.";

    return `# Technical Specifications

## Architecture
${context.specs.architecture || "Standard modern web architecture"}

## Technology Stack
- **Frontend:** ${context.specs.techStack?.frontend?.join(", ") || "Next.js, Tailwind CSS"}
- **Backend:** ${context.specs.techStack?.backend?.join(", ") || "Next.js API Routes"}
- **Database:** ${context.specs.techStack?.database?.join(", ") || "Local storage"}

## API Endpoints
${context.specs.apiEndpoints?.map(e => `- **${e.method} ${e.path}**: ${e.description} (Auth: ${e.authRequired ? "Yes" : "No"})`).join("\n") || "None defined"}

## Database Schema
${context.specs.databaseSchema?.tables?.map(t => `
### Table: ${t.name}
| Column | Type | Constraints |
|---|---|---|
| ${t.columns?.map(c => `${c.name} | ${c.type} | ${c.constraints?.join(", ") || ""}`).join("\n| ")} |
`).join("\n") || "None defined"}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderUserFlows(context: LivingContext): string {
    if (!context.flows || !Array.isArray(context.flows)) return "# User Flows\n\nNo user flows defined yet.";

    return `# User Flows

${context.flows.map(f => `
### ${f.name || "Unnamed Flow"}
**Description:** ${f.description || "N/A"}
**Actors:** ${f.actors?.join(", ") || "User"}
**Steps:**
${f.steps?.map((s, i) => `${i + 1}. ${s}`).join("\n") || "None defined"}
`).join("\n---")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderEdgeCases(context: LivingContext): string {
    if (!context.edgeCases || !Array.isArray(context.edgeCases)) return "# Edge Cases\n\nNo edge cases defined yet.";

    return `# Edge Cases

${context.edgeCases.map(ec => `
### [${ec.category || "General"}] ${ec.description || "N/A"}
**Mitigation:** ${ec.mitigation || "N/A"}
`).join("\n---")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderComponentList(context: LivingContext): string {
    if (!context.components || !Array.isArray(context.components)) return "# Component Architecture\n\nNo components defined yet.";

    const groups: Record<string, any[]> = {};
    context.components.forEach(c => {
      const g = c.group || "Uncategorized";
      if (!groups[g]) groups[g] = [];
      groups[g].push(c);
    });

    return `# Component Architecture

${Object.entries(groups).map(([group, comps]) => `
## ${group}
${comps.map(c => `- **${c.name}**: ${c.description || "N/A"} (${c.type || "UI Component"}) [Status: ${c.status || "Planned"}]`).join("\n")}
`).join("\n")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }
  public static renderTypesGuide(context: LivingContext): string {
    const types = (context as any).brain?.types || { entities: [], shared: [] };
    return `# Architecture & Type Guide

## Core Entities
${(types.entities || []).map((e: any) => `
### ${e.name}
${e.description}
\`\`\`typescript
${e.schema}
\`\`\`
`).join("\n") || "None defined"}

## Shared Types
${(types.shared || []).map((s: any) => `
### ${s.name}
${s.description}
\`\`\`typescript
${s.schema}
\`\`\`
`).join("\n") || "None defined"}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderBrandGuide(context: LivingContext): string {
    const brand = (context as any).brain?.brand || { theme: "light", colors: {}, typography: {}, designPrinciples: [] };
    return `# Brand & Design Guidelines

## Visual Identity
**Theme:** ${brand.theme || "light"}
**Primary Color:** ${brand.colors?.primary || "N/A"}
**Background:** ${brand.colors?.background || "N/A"}

## Typography
**Font Family:** ${brand.typography?.fontFamily || "N/A"}
**Heading Scale:** ${brand.typography?.headingScale || "N/A"}

## Design Principles
${(brand.designPrinciples || []).map((p: any) => `- ${p}`).join("\n") || "N/A"}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }
}
