import { LivingContext } from "../types/living-context";

/**
 * ContextRenderer: Utility to render human-readable Markdown from the LivingContext JSON.
 */
export class ContextRenderer {
  public static renderPRD(context: LivingContext): string {
    return `# Product Requirements Document

## Project Overview
**Project Name:** ${context.metadata.projectConfig.name}
**Description:** ${context.metadata.projectConfig.description}

## Core Purpose
${context.prd.problemStatement}

## Goals
${context.prd.goals.map(g => `- ${g}`).join("\n")}

## Non-Goals
${context.prd.nonGoals?.map(g => `- ${g}`).join("\n") || "N/A"}

## Target Audience
${context.prd.targetAudience}

## Success Metrics
${context.prd.successMetrics.map(m => `- ${m}`).join("\n")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderFeatures(context: LivingContext): string {
    return `# Product Features

${context.features.map(f => `
### ${f.name} (${f.priority.toUpperCase()})
**Description:** ${f.description}
**Value:** ${f.userValue}
**Acceptance Criteria:**
${f.acceptanceCriteria.map(ac => `- [ ] ${ac}`).join("\n")}
**Dependencies:** ${f.dependencies.join(", ") || "None"}
`).join("\n---")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderTechnicalSpecs(context: LivingContext): string {
    return `# Technical Specifications

## Architecture
${context.specs.architecture}

## Technology Stack
- **Frontend:** ${context.specs.techStack.frontend.join(", ")}
- **Backend:** ${context.specs.techStack.backend.join(", ")}
- **Database:** ${context.specs.techStack.database.join(", ")}

## API Endpoints
${context.specs.apiEndpoints.map(e => `- **${e.method} ${e.path}**: ${e.description} (Auth: ${e.authRequired ? "Yes" : "No"})`).join("\n")}

## Database Schema
${context.specs.databaseSchema.tables.map(t => `
### Table: ${t.name}
| Column | Type | Constraints |
|---|---|---|
${t.columns.map(c => `| ${c.name} | ${c.type} | ${c.constraints?.join(", ") || ""} |`).join("\n")}
`).join("\n")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderUserFlows(context: LivingContext): string {
    return `# User Flows

${context.flows.map(f => `
### ${f.name}
**Description:** ${f.description}
**Actors:** ${f.actors.join(", ")}
**Steps:**
${f.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}
`).join("\n---")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderEdgeCases(context: LivingContext): string {
    return `# Edge Cases

${context.edgeCases.map(ec => `
### [${ec.category}] ${ec.description}
**Mitigation:** ${ec.mitigation}
`).join("\n---")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }
}
