import { LivingContext } from "../types/living-context";

/**
 * ContextRenderer: Utility to render human-readable Markdown from the LivingContext JSON.
 */
export class ContextRenderer {
  public static renderPRD(context: LivingContext): string {
    return `# Product Requirements Document

## Project Overview
**Project Name:** ${context.metadata.projectConfig.name}
**Description:** ${context.metadata.projectConfig.description}

## Core Purpose
${context.prd.problemStatement}

## Goals
${context.prd.goals.map(g => `- ${g}`).join("\n")}

## Non-Goals
${context.prd.nonGoals?.map(g => `- ${g}`).join("\n") || "N/A"}

## Target Audience
${context.prd.targetAudience}

## Success Metrics
${context.prd.successMetrics.map(m => `- ${m}`).join("\n")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderFeatures(context: LivingContext): string {
    return `# Product Features

${context.features.map(f => `
### ${f.name} (${f.priority.toUpperCase()})
**Description:** ${f.description}
**Value:** ${f.userValue}
**Acceptance Criteria:**
${f.acceptanceCriteria.map(ac => `- [ ] ${ac}`).join("\n")}
**Dependencies:** ${f.dependencies.join(", ") || "None"}
`).join("\n---")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderTechnicalSpecs(context: LivingContext): string {
    return `# Technical Specifications

## Architecture
${context.specs.architecture}

## Technology Stack
- **Frontend:** ${context.specs.techStack.frontend.join(", ")}
- **Backend:** ${context.specs.techStack.backend.join(", ")}
- **Database:** ${context.specs.techStack.database.join(", ")}

## API Endpoints
${context.specs.apiEndpoints.map(e => `- **${e.method} ${e.path}**: ${e.description} (Auth: ${e.authRequired ? "Yes" : "No"})`).join("\n")}

## Database Schema
${context.specs.databaseSchema.tables.map(t => `
### Table: ${t.name}
| Column | Type | Constraints |
|---|---|---|
${t.columns.map(c => `| ${c.name} | ${c.type} | ${c.constraints?.join(", ") || ""} |`).join("\n")}
`).join("\n")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderUserFlows(context: LivingContext): string {
    return `# User Flows

${context.flows.map(f => `
### ${f.name}
**Description:** ${f.description}
**Actors:** ${f.actors.join(", ")}
**Steps:**
${f.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}
`).join("\n---")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderEdgeCases(context: LivingContext): string {
    return `# Edge Cases

${context.edgeCases.map(ec => `
### [${ec.category}] ${ec.description}
**Mitigation:** ${ec.mitigation}
`).join("\n---")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderComponentList(context: LivingContext): string {
    const groups: Record<string, any[]> = {};
    context.components.forEach(c => {
      const g = c.group || "Uncategorized";
      if (!groups[g]) groups[g] = [];
      groups[g].push(c);
    });

    return `# Component Architecture

${Object.entries(groups).map(([group, comps]) => `
## ${group}
${comps.map(c => `- **${c.name}**: ${c.description} (${c.type}) [Status: ${c.status}]`).join("\n")}
`).join("\n")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }
  public static renderTypesGuide(context: LivingContext): string {
    const types = (context.brain as any)?.types || { entities: [], shared: [] };
    return `# Architecture & Type Guide

## Core Entities
${(types.entities || []).map((e: any) => `
### ${e.name}
${e.description}
\`\`\`typescript
${e.schema}
\`\`\`
`).join("\n")}

## Shared Types
${(types.shared || []).map((s: any) => `
### ${s.name}
${s.description}
\`\`\`typescript
${s.schema}
\`\`\`
`).join("\n")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }

  public static renderBrandGuide(context: LivingContext): string {
    const brand = (context.brain as any)?.brand || { theme: "light", colors: {}, typography: {}, designPrinciples: [] };
    return `# Brand & Design Guidelines

## Visual Identity
**Theme:** ${brand.theme || "light"}
**Primary Color:** ${brand.colors?.primary || "N/A"}
**Background:** ${brand.colors?.background || "N/A"}

## Typography
**Font Family:** ${brand.typography?.fontFamily || "N/A"}
**Heading Scale:** ${brand.typography?.headingScale || "N/A"}

## Design Principles
${(brand.designPrinciples || []).map((p: any) => `- ${p}`).join("\n")}

---
*Generated by MyContext CLI - Living Brain JSON Source*
`;
  }
}
